# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  GO111MODULE: 'on'

jobs:
  - job: 'goamqp'
    displayName: 'Run go-amqp CI Checks'


    pool:
      vmImage: ubuntu-latest

    steps:
      - task: GoTool@0
        inputs:
          version: '1.19'
        displayName: "Select Go Version"

      - script: |
          set -e
          export gopathbin=$(go env GOPATH)/bin
          echo "##vso[task.prependpath]$gopathbin"
          go install github.com/jstemmer/go-junit-report@v0.9.1
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/AlekSi/gocov-xml@v1.0.0
          go install github.com/matm/gocov-html/cmd/gocov-html@v1.2.0
        displayName: 'Install Dependencies'

      - script: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          golangci-lint --version
          golangci-lint run
        displayName: 'Install and Run GoLintCLI.'

      - script: |
          go build -v ./...
        displayName: 'Build'

      - script: |
          go vet ./...
        displayName: 'Vet'
        

